name: jogo_da_velha_f
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+41

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  confetti: ^0.8.0
  audioplayers: ^6.5.1
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # O pacote de ícones tem de estar aqui!

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/click.mp3
    - assets/sounds/winner.mp3

# A CONFIGURAÇÃO DO ÍCONE FICA TOTALMENTE ENCOSTADA À ESQUERDA
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21